;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-or-skip-quote
        beginning-of-buffer
        describe-key
        eval-last-sexp
        forward-sentence
        mouse-yank-primary
        overwrite-mode
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill-region-or-backward-word
        smex
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        kill-region
        kill-region-or-backward-word
        mark-paragraph
        webjump
        ))
